use crate::pwire::Value;

/// Escape a SQL string value using single-quote escaping.
/// Handles single quotes, backslashes, null bytes, and control characters.
pub fn escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        match ch {
            '\'' => out.push_str("''"),
            '\\' => out.push_str("\\\\"),
            '\0' => out.push_str("\\0"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\x08' => out.push_str("\\b"),
            '\x1a' => out.push_str("\\Z"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}

/// Escape binary data as a hex literal: X'deadbeef'
pub fn escape_bytes(data: &[u8]) -> String {
    let mut out = String::with_capacity(data.len() * 2 + 3);
    out.push_str("X'");
    for byte in data {
        out.push_str(&format!("{:02x}", byte));
    }
    out.push('\'');
    out
}

/// Quote an identifier (table name, column name) with backticks.
/// Escapes any backtick inside the identifier by doubling it.
pub fn quote_identifier(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 2);
    out.push('`');
    for ch in name.chars() {
        if ch == '`' {
            out.push('`');
        }
        out.push(ch);
    }
    out.push('`');
    out
}

/// Format a Value as a SQL literal for INSERT statements.
pub fn format_value(val: &Value) -> String {
    match val {
        Value::Null => "NULL".to_string(),
        Value::I64(v) => v.to_string(),
        Value::F64(v) => {
            if v.is_nan() {
                "'NaN'".to_string()
            } else if v.is_infinite() {
                if *v > 0.0 {
                    "'Infinity'".to_string()
                } else {
                    "'-Infinity'".to_string()
                }
            } else {
                // Use enough precision to round-trip
                format!("{:.17e}", v)
            }
        }
        Value::Text(s) => escape_string(s),
        Value::Bool(b) => {
            if *b {
                "TRUE".to_string()
            } else {
                "FALSE".to_string()
            }
        }
        Value::Bytes(data) => escape_bytes(data),
    }
}

/// Format a row of values as a parenthesized tuple for INSERT.
pub fn format_row(row: &[Value]) -> String {
    let parts: Vec<String> = row.iter().map(|v| format_value(v)).collect();
    format!("({})", parts.join(", "))
}

/// Format the column list for INSERT INTO.
pub fn format_column_list(columns: &[String]) -> String {
    let quoted: Vec<String> = columns.iter().map(|c| quote_identifier(c)).collect();
    format!("({})", quoted.join(", "))
}

/// Build a complete INSERT statement with multiple value rows.
/// Batches into groups of `batch_size` rows per INSERT.
pub fn format_insert_statements(
    table: &str,
    columns: &[String],
    rows: &[Vec<Value>],
    batch_size: usize,
) -> Vec<String> {
    let mut statements = Vec::new();
    let col_list = format_column_list(columns);
    let quoted_table = quote_identifier(table);

    for chunk in rows.chunks(batch_size) {
        let value_tuples: Vec<String> = chunk.iter().map(|row| format_row(row)).collect();
        let stmt = format!(
            "INSERT INTO {} {} VALUES\n{};",
            quoted_table,
            col_list,
            value_tuples.join(",\n")
        );
        statements.push(stmt);
    }

    statements
}

/// Format the dump file header comment.
pub fn format_dump_header(database: &str) -> String {
    format!(
        "-- PyroSQL database dump\n\
         -- Database: {}\n\
         -- Generated by: pyrosql-dump v1.0.0\n\
         --\n\n\
         SET FOREIGN_KEY_CHECKS = 0;\n\n",
        database
    )
}

/// Format the dump file footer.
pub fn format_dump_footer() -> String {
    "\nSET FOREIGN_KEY_CHECKS = 1;\n\n-- Dump completed\n".to_string()
}
