APT::FTPArchive::Release::Origin "PyroSQL";
APT::FTPArchive::Release::Label "PyroSQL-stable";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 arm64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "PyroSQL apt repository (stable)";
